### ISSUE TITLE
Changes in radii branch break fv3-bundle build 

### ISSUE THREAD

**Issue by rtodling** [JCSDA-internal/eckit#19]
Benjamin,

I am sorry - but there is something seriously not working in eckit after you have changes in the radii branch. 

/gmao/advda/rtodling/4OPS/geosJEDI/Internal/fv3-bundle/eckit/src' '-I/discover/nobackup/projects/gmao/advda/rtodling/4OPS/geosJEDI/Internal/fv3-bundle/build-baselibs-intel-impi-19.1.0.166-release-geos/eckit/src' '-I/discover/nobackup/projects/gmao/advda/rtodling/4OPS/geosJEDI/Internal/fv3-bundle/eckit/src/eckit' '-I/discover/swdev/jcsda/modules/core/eigen/3.3.7/include/eigen3' '-O3' '-DNDEBUG' '-fPIC' '-std=gnu++11' -o 'CMakeFiles/eckit.dir/log/LogTarget.cc.o' -c '/discover/nobackup/projects/gmao/advda/rtodling/4OPS/geosJEDI/Internal/fv3-bundle/eckit/src/eckit/log/LogTarget.cc' -I/usr/local/intel/2020/compilers_and_libraries_2020.0.166/linux/mpi/intel64/include
eckit/src/eckit/CMakeFiles/eckit.dir/build.make:1486: recipe for target 'eckit/src/eckit/CMakeFiles/eckit.dir/log/LogTarget.cc.o' failed
make[2]: *** [eckit/src/eckit/CMakeFiles/eckit.dir/log/LogTarget.cc.o] Error 139
make[2]: *** Deleting file 'eckit/src/eckit/CMakeFiles/eckit.dir/log/LogTarget.cc.o'
make[2]: *** Waiting for unfinished jobs....
[ 19%] Building Fortran object fv3-jedi-lm/src/CMakeFiles/fv3jedilm.dir/dynamics/atmos_cubed_sphere/model_tlmadm/a2b_edge_adm.F90.o
[ 19%] Building Fortran object fv3-jedi-lm/src/CMakeFiles/fv3jedilm.dir/dynamics/atmos_cubed_sphere/model_tlmadm/a2b_edge_tlm.F90.o
CMakeFiles/Makefile2:6464: recipe for target 'eckit/src/eckit/CMakeFiles/eckit.dir/all' failed

**Comment by benjaminmenetrier** [comment]
Hi @rtodling, sorry for the compilation trouble, it was working fine on my workstation with GNU. Please use the `feature/variable_fixed_radii_nofckit` branch for SABER (see PR https://github.com/JCSDA-internal/saber/pull/31) and `release-stable` for `eckit` and `fckit` as usual.

**Comment by rtodling** [comment]
Benjamin,
I assume that's your original version with the additional rh_profile opt. That's what Dan suggested ... I am using it and it works - though I agree w/ Fabio that having both rh and rh_profile is confusing and these could be collapsed into a single opt.
Thanks
R

**Comment by benjaminmenetrier** [comment]
Not really, the `rh_profile/rv_profile` option disappears in `feature/variable_fixed_radii_nofckit` and should be replaced by `rh/rv`, which are now arrays all the time (see [here](https://github.com/JCSDA-internal/saber/blob/feature/variable_fixed_radii_nofckit/src/saber/bump/type_nam.F90)). Can you try to `git pull` the branch again?
