### ISSUE TITLE
ecbuild problem when support for AEC is found

### ISSUE THREAD

**Issue by jmrosinski** [JCSDA-internal/eckit#2]
Building the latest ufo bundle on my Linux laptop, it failed and quit when trying to build executable eckit-dhcopy because it couldn't find entry points for aec_encode* and aec_decode* functions. The ecbuild log indicated however that it found libaec.so and was therefore going to enable support for it. In all builds I'm aware of so far that are working (hera, Mac), ecbuild indicates that it CANNOT find libaec.so and therefore disables support for it.

I don't fully understand what is going on, but a solution that worked on my laptop was to add the following to the "ecbuild" command AFTER the blank "--" line:

	-DENABLE_AEC=NO

After doing that the ufo bundle build ran to completion. Thought I'd share that since others may run into the same problem.

**Comment by markjolah** [comment]
@jmrosinski Just saw this now, as the JCSDA/eckit repo must not be part of any zenhub boards.  Do you happen to know which version of aec library you have installed?  Maybe this code was intendedness for a different version and we can fix it by checking the version in the CMake `find_package()` call.

**Comment by jmrosinski** [comment]
Yes "apt list" comes back with:

libaec-dev/bionic,now 0.3.2-2 amd64 [installed]

Though I did upgrade the OS recently from mint 19.0 to mint 19.2, so don't know whether libaec version changed or not. Though the time stamp on the lib file says Jul 28 2017 so I doubt that it changed.
