### ISSUE TITLE
eckit version for jedi

### ISSUE THREAD

**Issue by Gibies** [JCSDA-internal/eckit#20]
I got a message quoted below when tried to build fv3_bundle as follows

cd ${WRKDIR}
git clone https://github.com/JCSDA/fv3-bundle.git
ecbuild ${WRKDIR}/fv3-bundle
_______________________________________________________________
  CRITICAL - Please define a version for eckit

        project( eckit VERSION x.x.x LANGUAGES C CXX Fortran )
_______________________________________________________________

Can anybody suggest how to resolve this? I am a fresher to the JEDI community.

**Comment by shlyaeva** [comment]
@Gibies is this still an issue?

**Comment by climbfuji** [comment]
No updated/feedback since Dec 15, 2021. Also, eckit is now built as an external package in spack-stack.
